Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/noble64"
  config.vm.hostname = "ubuntu24"
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu24"
    vb.memory = 1024
    vb.cpus = 1
  end
end

